apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: azuremonitor-ingestion
    name: azuremonitor-ingestion
    namespace: observability
spec:
    replicas: 1
    selector:
        matchLabels:
            app: azuremonitor-ingestion
    template:
        metadata:
            labels:
                app: azuremonitor-ingestion
            name: azuremonitor-ingestion
        spec:
            containers:
            - name: aad-auth-proxy
              image: mcr.microsoft.com/azuremonitor/auth-proxy/prod/aad-auth-proxy/images/aad-auth-proxy:0.1.0-main-05-24-2023-b911fe1c
              imagePullPolicy: Always
              ports:
              - name: auth-port
                containerPort: 8081
              env:
              # (Required) Audience
              - name: AUDIENCE
                value: https://monitor.azure.com/.default
              # (Required) Azure Monitor workspace ingestion endpoint
              - name: TARGET_HOST
                value: https://azure-monitor-workspace.eastus-1.metrics.ingest.monitor.azure.com
              # (Required) Listening port for the proxy
              - name: LISTENING_PORT
                value: "8081"
              # (Required) Identity type - aadapplication
              - name: IDENTITY_TYPE
                value: aadapplication
              # (Required) AAD application client ID
              - name: AAD_CLIENT_ID
                value: <AAD-APPLICATION-CLIENT-ID>
              # (Required) AAD application tenant ID
              - name: AAD_TENANT_ID
                value: <AAD-TENANT-ID>
              # (Required) AAD application client certificate path
              - name: AAD_CLIENT_CERTIFICATE_PATH
                value: <PATH-TO-CERTIFICATE>
              # (Optional) Token refresh duration in percentage
              - name: AAD_TOKEN_REFRESH_INTERVAL_IN_PERCENTAGE
                value: "10"
              # (Optional) OTEL collector endpoint, proxy will send traces and metrics if passsed
              - name: OTEL_GRPC_ENDPOINT
                value: "otel-collector.observability.svc.cluster.local:4317"
              # (Optional) OTEL service name, so that you cna identify the proxy in traces and metrics
              - name: OTEL_SERVICE_NAME
                value: azuremonitor_ingestion
---
apiVersion: v1
kind: Service
metadata:
    name: azuremonitor-ingestion
    namespace: observability
spec:
    ports:
        - port: 80
          targetPort: 8081
    selector:
        app: azuremonitor-ingestion
