{
 "title": "Aad-Auth-Proxy",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "jobs",
    "label": "jobs",
    "query": {
     "query": "label_values(aad_auth_proxy_requests_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Token Refresh",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Token refresh by is_success",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(is_success) (aad_auth_proxy_token_refresh_total{job=~\"$jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token refresh by audience",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(audience) (aad_auth_proxy_token_refresh_total{job=~\"$jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Token refresh by is_success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count by(is_success) (increase(aad_auth_proxy_token_refresh_total{job=~\"$jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests count by status code",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(status_code) (aad_auth_proxy_requests_total{job=~\"$jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests count by user agent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(user_agent) (aad_auth_proxy_requests_total{job=~\"$jobs\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(status_code) (increase(aad_auth_proxy_requests_total{job=~\"$jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration (p95)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aad_auth_proxy_request_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request bytes by path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by(path) (rate(aad_auth_proxy_request_bytes_total{job=~\"$jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request bytes by user agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum by(user_agent) (rate(aad_auth_proxy_request_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response bytes by path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum by(path) (rate(aad_auth_proxy_response_bytes_total{job=~\"$jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Response bytes by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "sum by(status_code) (rate(aad_auth_proxy_response_bytes_total{job=~\"$jobs\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}